### PR TITLE
Feature proposal: Add hooks around fetch single result from curosr

### PR DESCRIPTION
**Pull request by blockjon**
I'd like to track how long it takes to fetch an item across the db handle when I do a fetchSingleResult. Seems like this is a way to do it. Seeking comment.

### CODE REVIEW

**Comment by alcaeus** [comment]
To be honest, I'm not sure adding events purely for measuring time is something you should need:
- if you want to track how fast/slow PHP code is, use a profiler like Blackfire or Tideways.
- if you need to figure out which queries are run, you can add a logger to the configuration to have instances of `LoggableCollection` which logs every query to a logger of your choice.

I'm not sure what else those events could be useful for, maybe you could elaborate a bit?

**Comment by alcaeus** [comment]
Just adding one more comment because I knew there were some logging things going around before the 1.2 release. If you're interested in logging that the driver and MongoDB itself are doing, @jmikola [previously recommended](https://github.com/doctrine/mongodb/issues/151#issuecomment-114252226) using [stream context listeners](https://secure.php.net/manual/en/mongo.context.php) in the driver.

**Comment by blockjon** [comment]
I have a different perspective, perhaps because I'm used to simpler database like MySQL.

In MySQL frameworks, it is very easy to measure query performance from the perspective of PHP because there's a very clear moment when the query takes place.

With Doctrine ODM, the moment that that the query takes place is hidden within the Cursor class. The query is implicitly executed as a consequence of trying to convert the results to an array.

With our application, we are concerned with how long our queries are taking from the PHP perspective. I want to be able to add instrumentation using our current instrumentation framework.

It is my opinion that the moment a query fires is a crucial moment in the control flow of any application and we should have a very elegant and simple way to have hooks around that moment within the ODM. Tooks like XHProf, Blackfire, and Tideways are things which we've looked at to perform profiling and sampling of the live environment for brief periods of time, but we are looking for a solution to allow us to instrument query performance long term.

**Comment by blockjon** [comment]
@alcaeus ^

**Comment by blockjon** [comment]
The exact ticket I'm working on right now has on it:

"It would be great to be able to measure timing of different specific queries (for instance, timing of just a primary key query, versus of a scatter get, etc.)."

I'm not even sure how I would do that with with the ODM since the query is prepared in one area and its executed in another area.

Ideally, I would have code that *roughly* could do this:

```
$query = .....;
$startTimer = now;
$result = $query->execute();
$ms = $now - $startTimer;
if ($query->isScatterGet()) {
  $instrument->increment('suboptimalmongoscattergetquery', $ms);
  $log->info("Scatter get query detected: $query->toString() took $ms to execute.");
} else {
  $instrument->increment('optimalprimarykeyquery', $ms);
}
```

**Comment by alcaeus** [comment]
Queries in doctrine/mongodb are just objects that hold a query array, an optional update array and some options. When you call `$query->execute()`, you get a cursor back, that's it. There is no explanation of the query attached to the cursor you're getting back, so you won't know whether that was an optimal or a suboptimal query.

As I've said before, the use case in question would best be covered logging these things either at the database level (check out the instrumentation provided by MongoDB itself, e.g. MMS) or at the driver level.

**Pull request closed without merging**
